apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  containers:
    - name: traffic-generator
      image: madavila/traffic-generator:2.0
      args:
        - 'reactor-service/reactor'
        - '1.0'